name: flutter_custom_shaper
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/iamtvirani/flutter_custom_shaper
repository: https://github.com/iamtvirani/flutter_custom_shaper

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
